language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
  - memcached
install:
  - composer install
before_script:
  - mysql -e 'create database basicobject;'
  - cp tests/.travis.settings.php tests/settings.php
script:
  - tests/tests.sh
